SELECT  B.COD_CEN
       ,B.NUM_DND
       ,B.IDT_TML
       ,A.CED_2
       ,A.CED_5
       ,A.CED_10
       ,A.CED_20
       ,A.CED_50
       ,A.CED_100
       ,A.CED_200
       ,A.VLR
       ,B.VLR_ABT_PRG
	   ,C.COMP
FROM [MERCANTIL\B039918].TI_AJUSTE_COMP A
LEFT JOIN
(
	SELECT  *
	FROM
	(
		SELECT  DISTINCT A.IDT_TML
		       ,A.NUM_DND
		       ,B.COD_TESOURARIA AS COD_CEN 
               , A.SUPRIMENTO_SUGERIDO 
               , A.SUPRIMENTO_PROGRAMADO_D1
		       ,CASE WHEN (
		SELECT  SUM(SUPRIMENTO_PROGRAMADO_D1)
		FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS]
        ) > 0 THEN A.SUPRIMENTO_PROGRAMADO_D1 ELSE A.SUPRIMENTO_SUGERIDO END AS VLR_ABT_PRG
		FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] A
		LEFT JOIN [MERCANTIL\B038660].[TI_PRINCIPAL_ACOMPANHAMENTO] B
		ON A.NUM_DND = B.NUM_DND
		WHERE A.NUM_DND != 634
		AND A.TIPO_ABASTECIMENTO != 'Agência Normal'
		GROUP BY  A.IDT_TML
		         ,A.NUM_DND
		         ,B.COD_TESOURARIA
		         ,A.SUPRIMENTO_SUGERIDO
		         ,A.SUPRIMENTO_PROGRAMADO_D1
	) X
	WHERE X.VLR_ABT_PRG > 0 
) B
ON A.COD_CEN = B.COD_CEN AND
A.VLR = B.VLR_ABT_PRG
LEFT JOIN [MERCANTIL\B040466].TI_CAD_VLR_COMP C
ON A.VLR = C.VLR
WHERE B.IDT_TML IS NOT NULL
ORDER BY 1, 11
