--SQLGDNP, GNU
SELECT  *
FROM
(
	SELECT  Z.TECE
	       ,Z.BANCO
	       ,Z.TIPO_NUMERARIO
	       ,Z.VLR_CEDULA_MOEDA
	       ,Z.VALOR_TOTAL
	       ,Z.DESCRICAO
	       ,Z.TRANSACAO
	       ,Z.ATUALIZACAO
	       ,Z.DTA_PRG
	FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z
	UNION ALL
	SELECT  TECE
	       ,'BMB'      AS BANCO
	       ,TIPO_NUMERARIO
	       ,DENOMINACAO
	       ,SALDO_ATUAL
	       ,'Abertura' AS DES_JST
	       ,'Custódia'AS TRANSACAO
	       ,NULL       AS ATUALIZACAO
	       ,NULL DTA_PRG
	FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA
	UNION ALL
	SELECT  *
	       ,NULL AS DTA_PRG
	FROM [MERCANTIL\B039918].[TI_ESTRUTURA_CUSTODIA]
	UNION ALL
	SELECT  T.TECE
	       ,T.BANCO
	       ,T.TIPO_NUMERARIO
	       ,T.VLR_CEDULA_MOEDA
	       ,SUM(T.VALOR_TOTAL) AS VALOR_TOTAL
	       ,'Saldo'            AS DESCRICAO
	       ,'Saldo'            AS TRANSACAO
	       ,CAST(T.ATUALIZACAO AS DATE) ATUALIZACAO
	       ,T.DTA_PRG
	FROM
	(
		SELECT  Z.TECE
		       ,Z.BANCO
		       ,Z.TIPO_NUMERARIO
		       ,Z.VLR_CEDULA_MOEDA
		       ,Z.VALOR_TOTAL
		       ,Z.DESCRICAO
		       ,Z.TRANSACAO
		       ,Z.ATUALIZACAO
		       ,Z.DTA_PRG
		FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z
		UNION ALL
		SELECT  TECE
		       ,'BMB'      AS BANCO
		       ,TIPO_NUMERARIO
		       ,DENOMINACAO
		       ,SALDO_ATUAL
		       ,'Abertura' AS DES_JST
		       ,'Custódia'AS TRANSACAO
		       ,NULL       AS ATUALIZACAO
		       ,NULL       AS DTA_PRG
		FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA
	) T
	WHERE T.TRANSACAO != 'RECOLHIMENTO'
	AND ((T.TRANSACAO = 'Banco do Brasil' AND T.DTA_PRG = CAST(GETDATE() AS DATE)) OR (T.TRANSACAO != 'Banco do Brasil')) --AND T.TECE = 8001
	GROUP BY  T.TECE
	         ,T.BANCO
	         ,T.TIPO_NUMERARIO
	         ,T.VLR_CEDULA_MOEDA
	         ,CAST(T.ATUALIZACAO AS DATE)
	         ,T.DTA_PRG
) V
WHERE (V.TRANSACAO = 'Banco do Brasil' AND V.DTA_PRG = CAST(GETDATE() AS DATE)) OR (V.TRANSACAO != 'Banco do Brasil' )
AND V.TECE != 0
AND V.VALOR_TOTAL > 0