--SQLMBCORP, MBCORP
SELECT  B.COD_CEN
       ,SUM(A.VLR_SLD_ATL) AS VALOR_TOTAL
FROM CUSTODIA_MAPA A
    RIGHT JOIN MAPA_FECHAM_TESOUR B
        ON A.IDT_MAP_FCM_TSR = B.IDT_MAP_FCM_TSR
    INNER JOIN TIPO_DENOMIN_MAPA C
        ON A.IDT_TIP_DNR_MAP = C.IDT_TIP_DNR_MAP
    LEFT JOIN TIPO_MAPA_FECHAM D
        ON B.IDT_TIP_MAP = D.IDT_TIP_MAP
    LEFT JOIN CENTRALIZADORA_NUM G
        ON B.COD_CEN = G.COD_CEN
WHERE A.TIP_ESD_CDU = 'D'
AND A.DTA_CUS_MAP = (
SELECT  MIN(DATA_MOVIMENTO) AS D1
FROM
(
	SELECT  TOP (1) DATA_MOVIMENTO
	FROM D_CALENDARIO
	WHERE (DIA_UTIL = 'SIM')
	AND (DATA_MOVIMENTO < CONVERT(DATE, GETDATE()))
	ORDER BY DATA_MOVIMENTO DESC 
) AS A) AND B.COD_CEN IS NOT NULL AND A.VLR_SLD_ATL != 0 AND G.DTA_DTV IS NULL
