--SQLMBCORP, MBCORP
SELECT  DISTINCT E.DATA_MOVIMENTO
       ,E.COD_CEN
       ,A.DTA_CUS_MAP
FROM
(
	SELECT  MAX(A.DATA_MOVIMENTO) DATA_MOVIMENTO
	       ,E.*
	FROM D_CALENDARIO A WITH
	(NOLOCK
	)
	CROSS JOIN
	(
		SELECT  DISTINCT E.COD_CEN
		       ,E.DES_CEN
		       ,E.IDT_TRN
		FROM CENTRALIZADORA_NUM E WITH
		(NOLOCK
		)
		WHERE E.DTA_DTV IS NULL
	) E
	WHERE A.DIA_UTIL = 'Sim'
	AND A.DATA_MOVIMENTO BETWEEN GETDATE()-5 AND GETDATE()-1
	GROUP BY  E.COD_CEN
	         ,E.DES_CEN
	         ,E.IDT_TRN
) E
LEFT JOIN
(
	SELECT  DISTINCT A.*
	       ,D.DTA_CUS_MAP
	FROM MAPA_FECHAM_TESOUR A WITH
	(NOLOCK
	)
	LEFT JOIN
	(
		SELECT  D.IDT_MAP_FCM_TSR
		       ,D.DTA_CUS_MAP
		FROM CUSTODIA_MAPA D WITH
		(NOLOCK
		)
	) D
	ON D.IDT_MAP_FCM_TSR = A.IDT_MAP_FCM_TSR
) A
ON E.COD_CEN = A.COD_CEN AND A.DTA_CUS_MAP = E.DATA_MOVIMENTO
WHERE A.DTA_CUS_MAP IS NULL
