/*SELECT  A.COD_CEN
       ,CAST(B.CUSTODIA AS INT)                                                                                                                      AS CUSTODIA
       --,CAST(B.CUSTODIA * SUM(A.CED_2)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)   AS PERC_2
       --,CAST(B.CUSTODIA * SUM(A.CED_5)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)   AS PERC_5
       ,CAST(B.CUSTODIA * SUM(A.CED_10)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)/*+SUM(A.CED_200)*/) AS INT)  AS PERC_10
       ,CAST(B.CUSTODIA * SUM(A.CED_20)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)/*+SUM(A.CED_200)*/) AS INT)  AS PERC_20
       ,CAST(B.CUSTODIA * SUM(A.CED_50)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)/*+SUM(A.CED_200)*/) AS INT)  AS PERC_50
       ,CAST(B.CUSTODIA * SUM(A.CED_100)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)/*+SUM(A.CED_200)*/) AS INT) AS PERC_100
       --,CAST(B.CUSTODIA * SUM(A.CED_200)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT) AS PERC_200
	   ,0 as PERC_200
FROM
(
	SELECT  A.IDT_TML
	       ,A.NUM_DND
	       ,B.COD_CEN
	       ,A.VLR_PERFIL
	       ,C.COMP
	       ,C.CED_2
	       ,C.CED_5
	       ,C.CED_10
	       ,C.CED_20
	       ,C.CED_50
	       ,C.CED_100
	       ,C.CED_200
	FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] A
	LEFT JOIN [MERCANTIL\B040466].TC_INFO_AG_TSR_TML B
	ON A.IDT_TML = B.IDT_TML
	LEFT JOIN [MERCANTIL\B040466].TI_CAD_VLR_COMP C
	ON A.VLR_PERFIL = C.VLR
) A
LEFT JOIN
(
	SELECT  ALT.TECE
	       ,SUM(ALT.VALOR_TOTAL) AS CUSTODIA
	FROM [MERCANTIL\B042786].[TI_GESTAO_ALT_CUSTODIA] ALT
	WHERE ALT.TRANSACAO = 'Saldo Programação'
	GROUP BY  ALT.TECE
) B
ON A.COD_CEN = B.TECE
WHERE A.COD_CEN IN ( SELECT  DISTINCT B.TECE
FROM
(
	SELECT  C.TECE
	       ,C.TIPO_NUMERARIO
	       ,C.VLR_CEDULA_MOEDA
	       ,SUM(C.VALOR_TOTAL)                    AS VALOR
	       ,SUM(C.VALOR_rec)                      AS VALOR_REC
	       ,SUM(C.VALOR_TOTAL) + SUM(C.VALOR_rec) AS TOTAL
	FROM
	(
		SELECT  Z.TECE
		       ,Z.BANCO
		       ,Z.TIPO_NUMERARIO
		       ,Z.VLR_CEDULA_MOEDA
		       ,CASE WHEN Z.TRANSACAO = 'Recolhimento' THEN 0  ELSE Z.VALOR_TOTAL END AS VALOR_TOTAL
		       ,CASE WHEN Z.TRANSACAO = 'Recolhimento' AND BK.TECE IS NULL THEN Z.VALOR_TOTAL * (
		SELECT  CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1,2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1 THEN 0  ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
		WHERE A.D0 = CAST(GETDATE() AS DATE)) ELSE 0 END AS VALOR_REC , Z.DESCRICAO , Z.TRANSACAO , Z.ATUALIZACAO , Z.DTA_PRG
		FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z
		LEFT JOIN [MERCANTIL\B040466].[TI_BLACKLIST_RECOLHIMENTO_TECES] BK
		ON BK.TECE = Z.TECE
		WHERE ((TRANSACAO = 'Banco do Brasil' AND CAST(DTA_PRG AS date) = CAST(GETDATE() AS DATE)) OR TRANSACAO != 'Banco do Brasil') 
		UNION ALL
		SELECT  TECE
		       ,'BMB'      AS BANCO
		       ,TIPO_NUMERARIO
		       ,DENOMINACAO
		       ,SALDO_ATUAL
		       ,'0'        AS VALOR_REC
		       ,'Abertura' AS DES_JST
		       ,'Custódia'AS TRANSACAO
		       ,null       AS ATUALIZACAO
		       ,NULL DTA_PRG
		FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA
	) C
	WHERE C.TIPO_NUMERARIO = 'Cédula Nova Família'
	GROUP BY  C.TECE
	         ,C.TIPO_NUMERARIO
	         ,C.VLR_CEDULA_MOEDA
) B
GROUP BY  B.TECE
HAVING SUM(B.VALOR) >= 0 AND MIN (B.VALOR) >= 0)
GROUP BY  A.COD_CEN
         ,B.CUSTODIA
ORDER BY 1*/


SELECT  A.COD_CEN
       ,CAST(B.CUSTODIA AS INT)                                                                                                                      AS CUSTODIA
       --,CAST(B.CUSTODIA * SUM(A.CED_2)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)   AS PERC_2
       --,CAST(B.CUSTODIA * SUM(A.CED_5)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)   AS PERC_5
       ,CAST(B.CUSTODIA * SUM(A.CED_10)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)  AS PERC_10
       ,CAST(B.CUSTODIA * SUM(A.CED_20)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)  AS PERC_20
       ,CAST(B.CUSTODIA * SUM(A.CED_50)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT)  AS PERC_50
       ,CAST(B.CUSTODIA * SUM(A.CED_100)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT) AS PERC_100
       ,CAST(B.CUSTODIA * SUM(A.CED_200)/(SUM(A.CED_2)+SUM(A.CED_5)+SUM(A.CED_10)+SUM(A.CED_20)+SUM(A.CED_50)+SUM(A.CED_100)+SUM(A.CED_200)) AS INT) AS PERC_200
	   --,0 as PERC_200
FROM
(
	SELECT  A.IDT_TML
	       ,A.NUM_DND
	       ,B.COD_CEN
	       ,A.VLR_PERFIL
	       ,C.COMP
	       ,C.CED_2
	       ,C.CED_5
	       ,C.CED_10
	       ,C.CED_20
	       ,C.CED_50
	       ,C.CED_100
	       ,C.CED_200
	FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] A
	LEFT JOIN [MERCANTIL\B040466].TC_INFO_AG_TSR_TML B
	ON A.IDT_TML = B.IDT_TML
	LEFT JOIN [MERCANTIL\B040466].TI_CAD_VLR_COMP C
	ON A.VLR_PERFIL = C.VLR
) A
LEFT JOIN
(
	SELECT A.TECE
		,SUM(A.VALOR_TOTAL) AS CUSTODIA
	FROM
		(SELECT  V.TECE
				,V.BANCO
				,V.TIPO_NUMERARIO
				,V.VLR_CEDULA_MOEDA
				,V.VALOR_TOTAL
				,V.DESCRICAO
				,V.TRANSACAO
				,V.ATUALIZACAO
				,V.DTA_PRG
				,0 AS ALTERACAO
		FROM
		(
			SELECT  Z.TECE
				,Z.BANCO
				,Z.TIPO_NUMERARIO
				,Z.VLR_CEDULA_MOEDA
				,Z.VALOR_TOTAL
				,Z.DESCRICAO
				,Z.TRANSACAO
				,Z.ATUALIZACAO
				,Z.DTA_PRG
				,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
			FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z WITH (NOLOCK)

			UNION ALL

			SELECT  TECE
				,'BMB'      AS BANCO
				,TIPO_NUMERARIO
				,DENOMINACAO
				,SALDO_ATUAL
				,'Abertura' AS DES_JST
				,'Custódia'AS TRANSACAO
				,NULL       AS ATUALIZACAO
				,NULL DTA_PRG
				,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
			FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA WITH (NOLOCK)

			UNION ALL

			SELECT  *
				,NULL AS DTA_PRG
				,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
			FROM [MERCANTIL\B039918].[TI_ESTRUTURA_CUSTODIA] WITH (NOLOCK)
			UNION ALL
			SELECT  T.TECE
				,T.BANCO
				,T.TIPO_NUMERARIO
				,T.VLR_CEDULA_MOEDA
				,SUM(T.VALOR_TOTAL) AS VALOR_TOTAL
				,'Saldo'            AS DESCRICAO
				,'Saldo'            AS TRANSACAO
				,CAST(T.ATUALIZACAO AS DATE) ATUALIZACAO
				,T.DTA_PRG
				,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
			FROM
			(
				SELECT  Z.TECE
					,Z.BANCO
					,Z.TIPO_NUMERARIO
					,Z.VLR_CEDULA_MOEDA
					,Z.VALOR_TOTAL
					,Z.DESCRICAO
					,Z.TRANSACAO
					,Z.ATUALIZACAO
					,Z.DTA_PRG
					,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
				FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z WITH (NOLOCK)

				UNION ALL

				SELECT  TECE
					,'BMB'      AS BANCO
					,TIPO_NUMERARIO
					,DENOMINACAO
					,SALDO_ATUAL
					,'Abertura' AS DES_JST
					,'Custódia'AS TRANSACAO
					,NULL       AS ATUALIZACAO
					,NULL       AS DTA_PRG
					,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
			THEN 0 ELSE 0.5 END AS PERC_REC
		FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A WITH (NOLOCK)
		WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
				FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA WITH (NOLOCK)
			) T
			WHERE T.TRANSACAO != 'RECOLHIMENTO'
			AND ((T.TRANSACAO = 'Banco do Brasil' AND T.DTA_PRG = CAST(GETDATE() AS DATE)) OR (T.TRANSACAO != 'Banco do Brasil')) --AND T.TECE = 8001
			GROUP BY  T.TECE
					,T.BANCO
					,T.TIPO_NUMERARIO
					,T.VLR_CEDULA_MOEDA
					,CAST(T.ATUALIZACAO AS DATE)
					,T.DTA_PRG
		) V
		LEFT JOIN [MERCANTIL\B040466].[TI_BLACKLIST_RECOLHIMENTO_TECES] AS BK WITH (NOLOCK)
		ON V.TECE = BK.TECE
		WHERE (V.TRANSACAO = 'Banco do Brasil' AND V.DTA_PRG = CAST(GETDATE() AS DATE)) OR (V.TRANSACAO != 'Banco do Brasil' )
		AND V.TECE != 0
		AND V.VALOR_TOTAL != 0)
	A
	WHERE A.DESCRICAO = 'Saldo'
	AND A.TIPO_NUMERARIO = 'Cédula Nova Família'
	GROUP BY A.TECE
) B
ON A.COD_CEN = B.TECE
GROUP BY  A.COD_CEN
         ,B.CUSTODIA
ORDER BY 1
