SELECT  AG.IDT_TML
       ,AB.DTA_HOR_PRG
       ,AB.VLR_ABT_PRG
FROM ABASTEC_PROGRAMADO AB
INNER JOIN TML_AGENCIA AG
ON AB.IDT_TML_DND = AG.IDT_TML_DND
WHERE cast(DTA_HOR_PRG AS date) > CAST(GETDATE() AS date)
--AND DATEPART(HOUR, AB.DTA_HOR_PRG) != 0
