--SQLGDNP, GNU
SELECT  
	 V.TECE
	,V.TIPO_NUMERARIO
	,V.VLR_CEDULA_MOEDA AS CEDULA
	,SUM(CASE WHEN V.TRANSACAO = 'Recolhimento' AND BK.TECE IS NULL THEN V.VALOR_TOTAL * V.PERC_REC
		WHEN V.TRANSACAO = 'Saldo' THEN V.VALOR_TOTAL
		ELSE 0
		END) AS VALOR_TOTAL
FROM
(
	SELECT  Z.TECE
	       ,Z.BANCO
	       ,Z.TIPO_NUMERARIO
	       ,Z.VLR_CEDULA_MOEDA
	       ,Z.VALOR_TOTAL
	       ,Z.DESCRICAO
	       ,Z.TRANSACAO
	       ,Z.ATUALIZACAO
	       ,Z.DTA_PRG
		   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
	FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z

	UNION ALL

	SELECT  TECE
	       ,'BMB'      AS BANCO
	       ,TIPO_NUMERARIO
	       ,DENOMINACAO
	       ,SALDO_ATUAL
	       ,'Abertura' AS DES_JST
	       ,'Custódia'AS TRANSACAO
	       ,NULL       AS ATUALIZACAO
	       ,NULL DTA_PRG
		   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
	FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA

	UNION ALL

	SELECT  *
	       ,NULL AS DTA_PRG
		   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
	FROM [MERCANTIL\B039918].[TI_ESTRUTURA_CUSTODIA]
	UNION ALL
	SELECT  T.TECE
	       ,T.BANCO
	       ,T.TIPO_NUMERARIO
	       ,T.VLR_CEDULA_MOEDA
	       ,SUM(T.VALOR_TOTAL) AS VALOR_TOTAL
	       ,'Saldo'            AS DESCRICAO
	       ,'Saldo'            AS TRANSACAO
	       ,CAST(T.ATUALIZACAO AS DATE) ATUALIZACAO
	       ,T.DTA_PRG
		   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
	FROM
	(
		SELECT  Z.TECE
		       ,Z.BANCO
		       ,Z.TIPO_NUMERARIO
		       ,Z.VLR_CEDULA_MOEDA
		       ,Z.VALOR_TOTAL
		       ,Z.DESCRICAO
		       ,Z.TRANSACAO
		       ,Z.ATUALIZACAO
		       ,Z.DTA_PRG
			   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
		FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z

		UNION ALL

		SELECT  TECE
		       ,'BMB'      AS BANCO
		       ,TIPO_NUMERARIO
		       ,DENOMINACAO
		       ,SALDO_ATUAL
		       ,'Abertura' AS DES_JST
		       ,'Custódia'AS TRANSACAO
		       ,NULL       AS ATUALIZACAO
		       ,NULL       AS DTA_PRG
			   ,(SELECT CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1, 2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1
	THEN 0 ELSE 0.5 END AS PERC_REC
FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
WHERE A.D0 = CAST(GETDATE() AS DATE)) AS PERC_REC
		FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA
	) T
	WHERE T.TRANSACAO != 'RECOLHIMENTO'
	AND ((T.TRANSACAO = 'Banco do Brasil' AND T.DTA_PRG = CAST(GETDATE() AS DATE)) OR (T.TRANSACAO != 'Banco do Brasil')) --AND T.TECE = 8001
	GROUP BY  T.TECE
	         ,T.BANCO
	         ,T.TIPO_NUMERARIO
	         ,T.VLR_CEDULA_MOEDA
	         ,CAST(T.ATUALIZACAO AS DATE)
	         ,T.DTA_PRG
) V
LEFT JOIN [MERCANTIL\B040466].[TI_BLACKLIST_RECOLHIMENTO_TECES] AS BK
ON V.TECE = BK.TECE
WHERE (V.TRANSACAO = 'Banco do Brasil' AND V.DTA_PRG = CAST(GETDATE() AS DATE)) OR (V.TRANSACAO != 'Banco do Brasil' )
AND V.TECE != 0
AND V.VALOR_TOTAL != 0
AND V.TRANSACAO IN ('Saldo', 'Recolhimento')
AND V.TIPO_NUMERARIO = 'Cédula Nova Família'

GROUP BY V.TECE
	,V.TIPO_NUMERARIO
	,V.VLR_CEDULA_MOEDA

ORDER BY V.TECE ,V.TIPO_NUMERARIO DESC, V.VLR_CEDULA_MOEDA DESC
