-- SQLGDNP / GNU **STATUS_CARD**
SELECT  B.TECE
       ,CASE WHEN SUM(B.VALOR) < 0 THEN 'Sem Cobertura'
             WHEN MIN(B.VALOR) < 0 THEN 'Alteração de Composição'  ELSE 'Em Conformidade' END                   AS DESCRICAO
       ,CASE WHEN MIN(B.TOTAL) < 0 THEN 0
             WHEN SUM(B.VALOR) < 0 AND SUM(B.TOTAL) >= 0 THEN 1
             WHEN SUM(B.VALOR) < 0 AND SUM(B.TOTAL) < 0 THEN 0
             WHEN SUM(B.VALOR) >= 0 AND MIN(B.VALOR) >= 0 THEN NULL  ELSE 1 END                                 AS REC_APOIA
       ,CASE WHEN MIN(B.TOTAL) < 0 AND /*SUM(B.TOTAL) >= 0 AND*/ MAX(B.OUTROS_NEGATIVOS) = 1 THEN 1  ELSE 0 END AS AJUSTE
       ,CASE WHEN MIN(B.TOTAL) < 0 AND /*SUM(B.TOTAL) >= 0 AND*/ MAX(B.TROCO_NEGATIVO) != 0 THEN 1  ELSE 0 END  AS DIMINUI_TROCO
FROM
(
	SELECT  *
	       ,CASE WHEN D.TOTAL < 0 AND D.VLR_CEDULA_MOEDA IN (2) THEN 1  ELSE 0 END     AS TROCO_NEGATIVO
	       ,CASE WHEN D.TOTAL < 0 AND D.VLR_CEDULA_MOEDA NOT IN (2) THEN 1  ELSE 0 END AS OUTROS_NEGATIVOS
	FROM
	(
		SELECT  C.TECE
		       ,C.TIPO_NUMERARIO
		       ,C.VLR_CEDULA_MOEDA
		       ,SUM(C.VALOR_TOTAL)                    AS VALOR
		       ,SUM(C.VALOR_rec)                      AS VALOR_REC
		       ,SUM(C.VALOR_TOTAL) + SUM(C.VALOR_rec) AS TOTAL
		FROM
		(
			SELECT  Z.TECE
			       ,Z.BANCO
			       ,Z.TIPO_NUMERARIO
			       ,Z.VLR_CEDULA_MOEDA
			       ,CASE WHEN Z.TRANSACAO = 'Recolhimento' THEN 0  ELSE Z.VALOR_TOTAL END AS VALOR_TOTAL
			       ,CASE WHEN Z.TRANSACAO = 'Recolhimento' AND BK.TECE IS NULL THEN Z.VALOR_TOTAL * (
						SELECT  CASE WHEN A.DIA_UTL_ANO_DTA_MO IN (1,2) OR A.DIA_UTL_ANO_DTA_MO >= A.MAIOR_DIA_MES - 1 THEN 0  ELSE 0.5 END AS PERC_REC
						FROM [MERCANTIL\B031076].TC_CALENDARIO_PAGTO A
						WHERE A.D0 = CAST(GETDATE() AS DATE)) 
					ELSE 0 END AS VALOR_REC , Z.DESCRICAO , Z.TRANSACAO , Z.ATUALIZACAO , Z.DTA_PRG
			FROM [MERCANTIL\B039918].TI_GESTAO_CUSTODIA Z
			LEFT JOIN [MERCANTIL\B040466].[TI_BLACKLIST_RECOLHIMENTO_TECES] BK
			ON BK.TECE = Z.TECE
			WHERE ((TRANSACAO = 'Banco do Brasil' AND CAST(DTA_PRG AS date) = CAST(GETDATE() AS DATE)) OR TRANSACAO != 'Banco do Brasil') 
			UNION ALL
			SELECT  TECE
			       ,'BMB'      AS BANCO
			       ,TIPO_NUMERARIO
			       ,DENOMINACAO
			       ,SALDO_ATUAL
			       ,'0'        AS VALOR_REC
			       ,'Abertura' AS DES_JST
			       ,'Custódia'AS TRANSACAO
			       ,null       AS ATUALIZACAO
			       ,NULL DTA_PRG
			FROM [MERCANTIL\B039918].CUSTODIA_PROVISORIA
		) C
		WHERE C.TIPO_NUMERARIO = 'Cédula Nova Família'
		GROUP BY  C.TECE
		         ,C.TIPO_NUMERARIO
		         ,C.VLR_CEDULA_MOEDA --HAVING SUM(C.VALOR_TOTAL) + SUM(C.VALOR_rec) < 0 --ORDER BY C.TECE ASC, C.VLR_CEDULA_MOEDA DESC
	) D --ORDER BY D.TECE ASC, D.VLR_CEDULA_MOEDA DESC
) B
GROUP BY  B.TECE