SELECT  X.IDT_TML
       ,X.COD_TESOURARIA      AS COD_CEN
       ,X.SUPRIMENTO_SUGERIDO AS VLR_ABT_PRG
       ,X.SUGESTAO_HORA       AS DTA_HOR_PRG
       ,X.NUM_DND
FROM
(
	SELECT  distinct A.*
	       ,B.QTDE_TML_TOTAL
	       ,B.QTDE_TML_INDISPONIVEL
	       ,B.TRANSPORTADORA
	       ,B.COD_TESOURARIA
	       ,B.TESOURARIA
	       ,B.COBERTURA_DISP_D1
	       ,B.COBERTURA_DISP_D2
	       ,B.COBERTURA_DISP_D0
	       ,B.RESPONSAVEL_TESOURARIA                                     AS RESPONSAVEL
	       ,B.COBERTURA_DISP_D1_SUP
	       ,CASE WHEN H.NUM_DND IS NOT NULL THEN 'S'  ELSE NULL END HR_ABSTEC_ESPECIFICO
	       ,H.HORA_ABASTEC_TRANSP HR_ESPECIFICO
	       ,CASE WHEN A.TIPO = 'NSZ' THEN 'SIM'
	             WHEN A.TIPO IS NULL THEN '-'  ELSE '-' END              AS IDC_NAO_SINALIZ
	       ,CASE WHEN A.SUPRIMENTO_PROGRAMADO > 0 THEN 1  ELSE 0 END     AS IDC_SUPRIMENTO_HOJE
	       ,CASE WHEN A.SALDO_TERMINAL_ATUAL <= 30000 THEN 1  ELSE 0 END AS IDC_SLD_MENOR_IGUAL_30
	       ,CASE WHEN A.NUM_DND IN ( SELECT NUM_DND FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] WHERE SALDO_TOTAL_FINAL_D1 < 100000) THEN 1  ELSE 0 END AS IDC_POSSUI_TML_MENOR_100
	       ,CASE WHEN A.NUM_DND IN ( SELECT NUM_DND FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] WHERE SALDO_TOTAL_FINAL_D1 < 50000) THEN 1  ELSE 0 END AS IDC_POSSUI_TML_MENOR_50
	FROM [MERCANTIL\B038660].[TI_PRINCIPAL_TERMINAIS] A
	LEFT JOIN [MERCANTIL\B038660].[TI_PRINCIPAL_ACOMPANHAMENTO] B
	ON A.NUM_DND = B.NUM_DND
	LEFT JOIN [MERCANTIL\B038660].TI_POSICAO_TERMINAL D
	ON A.IDT_TML = D.IDT_TML
	LEFT JOIN [MERCANTIL\B040466].TI_HORARIO_SUPRIMENTO_PONTOS H
	ON H.NUM_DND = A.NUM_DND
	WHERE A.NUM_DND != 634
	AND A.TIPO_ABASTECIMENTO != 'Agência Normal'
) X
WHERE X.SUPRIMENTO_SUGERIDO IS NOT NULL
AND X.SUPRIMENTO_SUGERIDO != 0
ORDER BY X.COD_TESOURARIA, X.SUPRIMENTO_SUGERIDO, X.IDT_TML
