--SQLGDNP, GNU
SELECT  A.*
       ,CASE WHEN B.QTDE > A.QTDE THEN A.QTDE  
       ELSE (
            CASE WHEN B.QTDE IS NULL THEN 0  
            ELSE B.QTDE END
            ) END AS ALTERACOES
FROM [MERCANTIL\B039918].TC_ATMS_PROG A
    LEFT JOIN [MERCANTIL\B039918].TI_AJUSTE_COMP B
    ON A.COD_CEN = B.COD_CEN AND A.PERFIL = B.VLR